### 1) Basic Array Creation 🍏

Create a 1D NumPy array containing the integers from 10 to 50, inclusive

<details><summary>Useful functions</summary>

```py
numpy.arange(start, stop, step)  # Returns an array of evenly spaced values within a given interval.
```
</details>

In [1]:
import numpy as np

arr = np.arange(10, 51)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


### 2) Array Arithmetic 🔢

Create two NumPy arrays of shape `(3, 3)`, filled with random integers between 1 and 20

Perform element-wise addition, subtraction, multiplication, and division

<details><summary>Useful functions</summary>

```py
numpy.random.randint(low, high, size)  # Returns an array of random integers from low (inclusive) to high (exclusive)
```
</details>

In [2]:
arr1 = np.random.randint(1, 21, size=(3, 3))
arr2 = np.random.randint(1, 21, size=(3, 3))

addition = arr1 + arr2
subtraction = arr1 - arr2
multiplication = arr1 * arr2
division = arr1 / arr2

print("Addition:\n", addition)
print("Subtraction:\n", subtraction)
print("Multiplication:\n", multiplication)
print("Division:\n", division)

Addition:
 [[ 9  4 17]
 [14 18 17]
 [22 20 10]]
Subtraction:
 [[ -5  -2 -11]
 [ -8  -6 -13]
 [ 10  14   8]]
Multiplication:
 [[14  3 42]
 [33 72 30]
 [96 51  9]]
Division:
 [[0.28571429 0.33333333 0.21428571]
 [0.27272727 0.5        0.13333333]
 [2.66666667 5.66666667 9.        ]]


### 3) Summing the Diagonals 🎲

Create a 5x5 matrix of random integers between 10 and 100

Calculate the sum of both the main diagonal and the anti-diagonal

<details><summary>Useful functions</summary>

```py
numpy.diag(array)    # Extracts the diagonal elements of an array
numpy.fliplr(array)  # Flips the array in the left/right direction
numpy.sum(array)     # Returns the sum of all elements in the array
```
</details>

In [3]:
matrix = np.random.randint(10, 101, size=(5, 5))

main_diag_sum = np.sum(np.diag(matrix))
anti_diag_sum = np.sum(np.diag(np.fliplr(matrix)))

print("Main diagonal sum:", main_diag_sum)
print("Anti-diagonal sum:", anti_diag_sum)

Main diagonal sum: 193
Anti-diagonal sum: 221


### 4) Fancy Indexing with Conditions 🔍

Generate a NumPy array of 100 random integers between 1 and 100

Find all elements that are divisible by 3 but not by 5 using array indexing

In [4]:
arr = np.random.randint(1, 101, size=100)

filtered = arr[(arr % 3 == 0) & (arr % 5 != 0)]

print(filtered)

[84  3  6 51 93 66 78 78 87 96  9 21 81 36 24 84 42 84 81 21 12]


### 5) Flatten, Sort, and Find 📏

Create a 6x6 matrix of random integers

Flatten it into a 1D array, sort the array, and find the 3 largest elements

<details><summary>Useful functions</summary>

```py
numpy.ndarray.ravel(array)  # Returns a flattened array
numpy.sort(array)           # Returns a sorted copy of the array
```
</details>

In [5]:
matrix = np.random.randint(1, 101, size=(6, 6))

flattened = matrix.ravel()
sorted_array = np.sort(flattened)
largest_3 = sorted_array[-3:]

print("3 largest elements:", largest_3)

3 largest elements: [89 95 97]


### 6) Normalize the Data 📈

Create a NumPy array with 20 random floating-point numbers between 0 and 1

Normalize this data so that the new values range between 0 and 100

> *Hint:* The formula for normalization is: $X_{\text{norm}} = \frac{X - X_{\text{min}}}{X_{\text{max}} - X_{\text{min}}} \times (\text{new-max} - \text{new-min}) + \text{new-min}$

<details><summary>Useful functions</summary>

```py
numpy.random.rand(size)  # Returns an array of random floats in the half-open interval [0.0, 1.0)
```
</details>

In [6]:
arr = np.random.rand(20)

normalized = (arr - arr.min()) / (arr.max() - arr.min()) * (100 - 0) + 0

print("Normalized array:", normalized)

Normalized array: [ 34.54822402 100.           0.          28.20571139  57.7750509
   0.45209101  22.56684599  88.32222371   5.03291633  21.64647402
  16.10629415  93.73326425  93.30524742  89.98142695  84.46033801
  77.15243936  48.68497834  90.65820631  92.40925564  55.70818011]


### 7) Broadcasting and Scaling 📊

Create a 4x5 matrix of random integers between 10 and 100

Subtract the column-wise mean from each element in the matrix

<details><summary>Useful functions</summary>

```py
numpy.ndarray.mean(array, axis)  # Returns the mean of the array along the specified axis
```
</details>

In [7]:
matrix = np.random.randint(10, 101, size=(4, 5))

column_means = matrix.mean(axis=0)
standardized = matrix - column_means

print("Column-wise mean subtracted:\n", standardized)

Column-wise mean subtracted:
 [[ -5.    15.75 -14.5  -43.5  -25.5 ]
 [ 12.   -16.25  -3.5   32.5   21.5 ]
 [-18.   -18.25 -24.5   44.5    3.5 ]
 [ 11.    18.75  42.5  -33.5    0.5 ]]


### 8) Matrix Multiplication Challenge 🤯

Create two matrices of size 4x3 and 3x5 with random integers

Perform matrix multiplication on them

<details><summary>Useful functions</summary>

```py
numpy.ndarray.dot(array1, array2)  # Returns the dot product of two arrays
```
</details>

In [8]:
matrix1 = np.random.randint(1, 10, size=(4, 3))
matrix2 = np.random.randint(1, 10, size=(3, 5))

result = np.dot(matrix1, matrix2)

print("Matrix multiplication result:\n", result)

Matrix multiplication result:
 [[ 52  95 139  49  86]
 [ 68  29  85  27  65]
 [ 91  62 127  49 107]
 [ 50  68 110  38  71]]


### 9) Find the Peaks 📉

Generate a 1D NumPy array with 20 random integers between 0 and 50

Identify the "peaks" (local maxima) in the array (local maxima)

> *Hint:* compare each element to its neighbors

In [9]:
arr = np.random.randint(0, 51, size=20)

peaks = arr[1:-1][(arr[1:-1] > arr[:-2]) & (arr[1:-1] > arr[2:])]

print("Peaks:", peaks)

Peaks: [48 17 24 23 45]


### 10) Simulate a Dice Roll 🎲🎲

Simulate rolling two six-sided dice 10,000 times

Count how many times the sum of the two dice equals 7

In [10]:
rolls = np.random.randint(1, 7, size=(10000, 2))

sums = rolls.sum(axis=1)
sevens = np.sum(sums == 7)

print("Number of times the sum is 7:", sevens)

Number of times the sum is 7: 1635
